ncommon_breadcrumb({
  'www.nintendo.co.jp': {
    '/index.html': {name: '任天堂ホームページ'},


    '/hardware/index.html': {name: '本体・amiibo：そのほかの本体', ignore: 1},

    '/hardware/switch/index.html': {name: '本体・amiibo：Nintendo Switch'},
    '/hardware/switch/lineup/index.html': {name: '本体ラインナップ'},
    '/hardware/switch/specs/index.html': {name: '機能・仕様'},
    '/hardware/switch/accessories/index.html': {name: '周辺機器'},
    '/hardware/switch/license/cover/index.html': {name: 'ライセンス商品（収納ケース・カバー）', parent: '/hardware/switch/accessories/index.html'},
    '/hardware/switch/license/sheet/index.html': {name: 'ライセンス商品（液晶保護シート）', parent: '/hardware/switch/accessories/index.html'},
    '/hardware/switch/license/card/index.html': {name: 'ライセンス商品（カードケース）', parent: '/hardware/switch/accessories/index.html'},
    '/hardware/switch/license/others/index.html': {name: 'ライセンス商品（その他）', parent: '/hardware/switch/accessories/index.html'},
    '/hardware/switch/onlineservice/index.html': {name: 'Nintendo Switch Online'},
    '/hardware/switch/onlineservice/onlineplay/index.html': {name: 'オンラインプレイ'},
    '/hardware/switch/onlineservice/fc/index.html': {name: 'ファミリーコンピュータ /スーパーファミコン Nintendo Switch Online'},
    '/hardware/switch/onlineservice/savedata/index.html': {name: 'セーブデータお預かり'},
    '/hardware/switch/onlineservice/app/index.html': {name: 'スマートフォン向けアプリ'},
    '/hardware/switch/onlineservice/specialoffer/index.html': {name: '加入者限定特典'},
    '/hardware/switch/onlineservice/faq/index.html': {name: 'よくあるご質問'},
    '/hardware/switch/onlineservice/pricing/index.html': {name: '料金プラン'},
    '/hardware/switch/parentalcontrols/index.html': {name: 'Nintendo みまもり Switch'},

    '/hardware/3dsseries/index.html': {name: '本体・amiibo：ニンテンドー3DSシリーズ'},
    '/hardware/3dsseries/accessories/index.html': {name: '周辺機器'},
    '/hardware/3dsseries/accessories/plate.html': {name: 'きせかえプレート'},
    '/hardware/3dsseries/compare/index.html': {name: 'シリーズを比較する'},
    '/hardware/3dsseries/specs/index.html': {name: '本体の主な仕様'},
    '/hardware/3dsseries/dlsoft/arakajime/index.html': {name: 'あらかじめダウンロードとは？'},
    '/hardware/3dsseries/new3dsll/index.html': {name: 'Newニンテンドー3DS LL'},
    '/hardware/3dsseries/new2dsll/index.html': {name: 'Newニンテンドー2DS LL'},
    '/hardware/3dsseries/2ds/index.html': {name: 'ニンテンドー2DS'},
    '/hardware/3dsseries/new3ds/index.html': {name: 'Newニンテンドー3DS'},
    '/hardware/3dsseries/3dsll/index.html': {name: 'ニンテンドー3DS LL'},
    '/hardware/3dsseries/3ds/index.html': {name: 'ニンテンドー3DS'},
    '/hardware/3dsseries/built-in/index.html': {name: '内蔵ソフト・その他'},
    '/hardware/3dsseries/miiverse/index.html': {name: 'Miiverse', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/browser/index.html': {name: 'インターネットブラウザー', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/internetbrowser/index.html': {name: 'インターネットブラウザー', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/miistudio/index.html': {name: 'Miiスタジオ', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/miiplaza/index.html': {name: 'すれちがいMii広場', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/miiplaza/fishing/index.html': {name: 'すれちがいフィッシング'},
    '/hardware/3dsseries/miiplaza/garden/index.html': {name: 'すれちがいガ～デン'},
    '/hardware/3dsseries/miiplaza/kabutrader/index.html': {name: 'サクッと! 株トレーダー'},
    '/hardware/3dsseries/miiplaza/kassen/index.html': {name: 'すれちがい合戦'},
    '/hardware/3dsseries/miiplaza/meikyu/index.html': {name: 'すれちがい迷宮'},
    '/hardware/3dsseries/miiplaza/shooting/index.html': {name: 'すれちがいシューティング'},
    '/hardware/3dsseries/miiplaza/slotcar/index.html': {name: 'サクッと! スロットカー'},
    '/hardware/3dsseries/miiplaza/taihouninja/index.html': {name: 'サクッと! 大砲忍者'},
    '/hardware/3dsseries/miiplaza/tankentai/index.html': {name: 'サクッと! 探検隊'},
    '/hardware/3dsseries/miiplaza/yushashokudo/index.html': {name: 'サクッと! 勇者食堂'},
    '/hardware/3dsseries/miiplaza/zombie/index.html': {name: 'すれちがいゾンビ'},
    '/hardware/3dsseries/camera/index.html': {name: 'ニンテンドー3DSカメラ', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/sound/index.html': {name: 'ニンテンドー3DSサウンド', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/ar/index.html': {name: 'ARゲームズ', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/face/index.html': {name: '顔シューティング', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/activitylog/index.html': {name: '思い出きろく帳', parent:'/hardware/3dsseries/built-in/index.html'},
    '/hardware/3dsseries/features/network.html': {name: 'すれちがい通信といつの間に通信'},
    '/hardware/3dsseries/streetpass_relay/index.html': {name: 'すれちがい通信中継所'},
    '/hardware/3dsseries/postimage/index.html': {name: 'ニンテンドー3DS画像投稿ツール'},
    '/hardware/3dsseries/lineup/pack/pokemon2ds/index.html': {name: 'ニンテンドー2DS『ポケットモンスター 赤・緑・青・ピカチュウ』限定パック'},
    '/hardware/3dsseries/theme/index.html': {name: 'いろんな「テーマ」で3DSをきせかえ。', name_short: 'テーマ'},
    '/hardware/3dsseries/theme/about/index.html': {name: '「テーマ」とは？'},
    '/hardware/3dsseries/theme/archive/index.html': {name: 'テーマ一覧', ignore: 1},
    '/hardware/3dsseries/theme/archive/201410.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201411.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201412.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201501.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201502.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201503.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201504.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201505.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201506.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201507.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201508.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201509.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201510.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201511.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201512.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201601.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201602.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201603.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201604.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201605.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201606.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201607.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201608.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201609.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201610.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201611.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201612.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201701.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201702.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201703.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201704.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201705.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201706.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201707.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201708.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201709.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201710.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201711.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201712.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201801.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201802.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201803.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201804.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201805.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201806.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201807.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201808.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201809.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201810.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201811.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201812.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/201901.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/fe.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/kirby.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/mario.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/mori.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/pokemon.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/shovel.html': {name: 'テーマ一覧'},
    '/hardware/3dsseries/theme/archive/zelda.html': {name: 'テーマ一覧'},

    '/hardware/amiibo/index.html': {name: '本体・amiibo：amiiboの特長'},
    '/hardware/amiibo/chart/index.html': {name: 'amiibo・ソフト対応表'},
    '/hardware/amiibo/diorama/index.html': {name: 'ジオラマキット'},
    '/hardware/amiibo/set/index.html': {name: 'セット商品'},
    '/hardware/amiibo/game/index.html': {name: '対応ソフト一覧', name_short: '対応ソフト'},
    '/hardware/amiibo/game/name.html': {name: '対応ソフト一覧', parent: '/hardware/amiibo/index.html'},
    '/hardware/amiibo/game/hardware.html': {name: '対応ソフト一覧', parent: '/hardware/amiibo/index.html'},
    '/hardware/amiibo/game/a9aj/index.html': {name: 'メトロイド サムスリターンズ'},
    '/hardware/amiibo/game/aaaca/index.html': {name: 'スーパーマリオ オデッセイ'},
    '/hardware/amiibo/game/aab6a/index.html': {name: 'スプラトゥーン2'},
    '/hardware/amiibo/game/aabpa/index.html': {name: 'マリオカート８ デラックス'},
    '/hardware/amiibo/game/aalj/index.html': {name: 'どうぶつの森 amiiboフェスティバル'},
    '/hardware/amiibo/game/aavj/index.html': {name: 'タッチ!amiibo いきなりファミコン名シーン'},
    '/hardware/amiibo/game/abaj/index.html': {name: 'マリオパーティ１０'},
    '/hardware/amiibo/game/abjj/index.html': {name: 'マリオ＆ソニック AT リオオリンピック™'},
    '/hardware/amiibo/game/adqj/index.html': {name: 'Miitopia'},
    '/hardware/amiibo/game/afxj/index.html': {name: 'スターフォックス　ゼロ'},
    '/hardware/amiibo/game/agmj/index.html': {name: 'Splatoon（スプラトゥーン）'},
    '/hardware/amiibo/game/ajbj/index.html': {name: 'Girls Mode 4 スター☆スタイリスト'},
    '/hardware/amiibo/game/ajjj/index.html': {name: 'ファイアーエムブレム Echoes もうひとりの英雄王'},
    '/hardware/amiibo/game/ajnj/index.html': {name: 'ポチと！ヨッシー ウールワールド'},
    '/hardware/amiibo/game/akbj/index.html': {name: '進め！キノピオ隊長'},
    '/hardware/amiibo/game/aksj/index.html': {name: 'ショベルナイト'},
    '/hardware/amiibo/game/amaj/index.html': {name: 'スーパーマリオメーカー'},
    '/hardware/amiibo/game/amkj/index.html': {name: 'マリオカート８'},
    '/hardware/amiibo/game/at3a/index.html': {name: '星のカービィ ロボボプラネット'},
    '/hardware/amiibo/game/aunj/index.html': {name: 'マリオスポーツ スーパースターズ'},
    '/hardware/amiibo/game/avxj/index.html': {name: 'マリオテニス ウルトラスマッシュ'},
    '/hardware/amiibo/game/axyj/index.html': {name: 'タッチ！カービィ スーパーレインボー'},
    '/hardware/amiibo/game/ay6a/index.html': {name: 'Code Name: S.T.E.A.M. リンカーンVSエイリアン'},
    '/hardware/amiibo/game/aycj/index.html': {name: 'ヨッシー ウールワールド'},
    '/hardware/amiibo/game/aynj/index.html': {name: 'マリオ＆ルイージRPG ペーパーマリオMIX'},
    '/hardware/amiibo/game/azaj/index.html': {name: 'ゼルダの伝説 トワイライトプリンセス HD'},
    '/hardware/amiibo/game/baaj/index.html': {name: 'マリオパーティ スターラッシュ'},
    '/hardware/amiibo/game/bbpj/index.html': {name: 'カタチ新発見！ 立体ピクロス２'},
    '/hardware/amiibo/game/bcaj/index.html': {name: 'メトロイドプライム フェデレーションフォース'},
    '/hardware/amiibo/game/bfwj/index.html': {name: 'ファイアーエムブレムif'},
    '/hardware/amiibo/game/bgxj/index.html': {name: 'マリオ＆ソニック AT リオオリンピック™'},
    '/hardware/amiibo/game/brcj/index.html': {name: 'Hey! ピクミン'},
    '/hardware/amiibo/game/brmj/index.html': {name: 'マリオ＆ルイージRPG1 DX'},
    '/hardware/amiibo/game/bwfj/index.html': {name: 'スターフォックス　ガード'},
    '/hardware/amiibo/game/bxlj/index.html': {name: 'なげなわアクション！ ぐるぐる！ちびロボ！'},
    '/hardware/amiibo/game/cafj/index.html': {name: 'ゼノブレイド （Newニンテンドー3DS専用ソフト）'},
    '/hardware/amiibo/game/ecdj/index.html': {name: 'ガールズモード キラキラ☆コーデ'},
    '/hardware/amiibo/game/edhj/index.html': {name: 'どうぶつの森 ハッピーホームデザイナー'},
    '/hardware/amiibo/game/egdj/index.html': {name: 'とびだせ どうぶつの森 amiibo+'},
    '/hardware/amiibo/game/aj8j/index.html': {name: 'カービィ バトルデラックス!'},
    '/hardware/amiibo/game/ja5j/index.html': {name: 'メトロイドプライム ブラストボール'},
    '/hardware/amiibo/game/jhua/index.html': {name: 'カービィのすいこみ大作戦'},
    '/hardware/amiibo/game/jlkj/index.html': {name: 'みんなで！カービィハンターズＺ'},
    '/hardware/amiibo/game/kckj/index.html': {name: 'さよなら！ハコボーイ！'},
    '/hardware/amiibo/game/bhrj/index.html': {name: 'マリオパーティ１００ ミニゲームコレクション'},
    '/hardware/amiibo/game/ae98a/index.html': {name: 'ベヨネッタ2'},
    '/hardware/amiibo/game/ap5j/index.html': {name: 'ミニマリオ ＆ フレンズ　amiiboチャレンジ'},
    '/hardware/amiibo/game/ah26a/index.html': {name: '星のカービィ　スターアライズ'},
    '/hardware/amiibo/game/smashbros/index.html': {name: '大乱闘スマッシュブラザーズ for Nintendo 3DS / Wii U'},
    '/hardware/amiibo/game/zelda/index.html': {name: 'ゼルダの伝説　ブレス オブ ザ ワイルド'},
    '/hardware/amiibo/game/ajh9a/index.html': {name: '進め！キノピオ隊長'},
    '/hardware/amiibo/game/ac2ga/index.html': {name: 'マリオ＋ラビッツ キングダムバトル'},
    '/hardware/amiibo/game/af3ca/index.html': {name: 'The Elder Scrolls V: Skyrim'},
    '/hardware/amiibo/game/awxj/index.html': {name: 'メイド イン ワリオ　ゴージャス'},
    '/hardware/amiibo/game/aaaba/index.html': {name: '大乱闘スマッシュブラザーズ SPECIAL'},
    '/hardware/amiibo/game/a3rj/index.html': {name: 'マリオ＆ルイージRPG3 DX'},
    '/hardware/amiibo/game/be4j/index.html': {name: '毛糸のカービィ プラス'},
    '/hardware/amiibo/game/aea2a/index.html': {name: 'ヨッシークラフトワールド'},
    '/hardware/amiibo/game/anvya/index.html': {name: 'ファイアーエムブレム 風花雪月'},
    '/hardware/amiibo/game/ar3na/index.html': {name: 'ゼルダの伝説 夢をみる島'},
    '/hardware/amiibo/game/apy8a/index.html': {name: 'スーパーカービィハンターズ'},
    '/hardware/amiibo/lineup/index.html': {name: 'ラインナップ一覧', name_short: 'ラインナップ'},
    '/hardware/amiibo/lineup/name.html': {name: 'ラインナップ一覧', parent: '/hardware/amiibo/index.html'},
    '/hardware/amiibo/lineup/series.html': {name: 'ラインナップ一覧', parent: '/hardware/amiibo/index.html'},
    '/hardware/amiibo/lineup/aaaa/index.html': {name: 'マリオ'},
    '/hardware/amiibo/lineup/aaab/index.html': {name: 'ピーチ'},
    '/hardware/amiibo/lineup/aaac/index.html': {name: 'ヨッシー'},
    '/hardware/amiibo/lineup/aaad/index.html': {name: 'ドンキーコング'},
    '/hardware/amiibo/lineup/aaae/index.html': {name: 'リンク'},
    '/hardware/amiibo/lineup/aaaf/index.html': {name: 'フォックス'},
    '/hardware/amiibo/lineup/aaag/index.html': {name: 'サムス'},
    '/hardware/amiibo/lineup/aaah/index.html': {name: 'Wii Fit トレーナー'},
    '/hardware/amiibo/lineup/aaaj/index.html': {name: 'むらびと'},
    '/hardware/amiibo/lineup/aaak/index.html': {name: 'ピカチュウ'},
    '/hardware/amiibo/lineup/aaal/index.html': {name: 'カービィ'},
    '/hardware/amiibo/lineup/aaam/index.html': {name: 'マルス'},
    '/hardware/amiibo/lineup/aaan/index.html': {name: 'ルイージ'},
    '/hardware/amiibo/lineup/aaap/index.html': {name: 'ディディーコング'},
    '/hardware/amiibo/lineup/aaaq/index.html': {name: 'ゼルダ'},
    '/hardware/amiibo/lineup/aaar/index.html': {name: 'リトル・マック'},
    '/hardware/amiibo/lineup/aaas/index.html': {name: 'ピット'},
    '/hardware/amiibo/lineup/aaat/index.html': {name: 'ルカリオ'},
    '/hardware/amiibo/lineup/aaau/index.html': {name: 'キャプテン・ファルコン'},
    '/hardware/amiibo/lineup/aaav/index.html': {name: 'ロゼッタ&チコ'},
    '/hardware/amiibo/lineup/aaaw/index.html': {name: 'クッパ'},
    '/hardware/amiibo/lineup/aaax/index.html': {name: 'クッパJr.'},
    '/hardware/amiibo/lineup/aaay/index.html': {name: 'トゥーンリンク'},
    '/hardware/amiibo/lineup/aaaz/index.html': {name: 'シーク'},
    '/hardware/amiibo/lineup/aaba/index.html': {name: 'アイク'},
    '/hardware/amiibo/lineup/aabb/index.html': {name: 'ドクターマリオ'},
    '/hardware/amiibo/lineup/aabc/index.html': {name: 'ワリオ'},
    '/hardware/amiibo/lineup/aabd/index.html': {name: 'ガノンドロフ'},
    '/hardware/amiibo/lineup/aabe/index.html': {name: 'ファルコ'},
    '/hardware/amiibo/lineup/aabf/index.html': {name: 'ゼロスーツサムス'},
    '/hardware/amiibo/lineup/aabg/index.html': {name: 'ピクミン＆オリマー'},
    '/hardware/amiibo/lineup/aabh/index.html': {name: 'パルテナ'},
    '/hardware/amiibo/lineup/aabj/index.html': {name: 'ブラックピット'},
    '/hardware/amiibo/lineup/aabk/index.html': {name: 'Mii 格闘タイプ'},
    '/hardware/amiibo/lineup/aabl/index.html': {name: 'Mii 剣術タイプ'},
    '/hardware/amiibo/lineup/aabm/index.html': {name: 'Mii 射撃タイプ'},
    '/hardware/amiibo/lineup/aabn/index.html': {name: 'リザードン'},
    '/hardware/amiibo/lineup/aabp/index.html': {name: 'ゲッコウガ'},
    '/hardware/amiibo/lineup/aabq/index.html': {name: 'プリン'},
    '/hardware/amiibo/lineup/aabr/index.html': {name: 'メタナイト'},
    '/hardware/amiibo/lineup/aabs/index.html': {name: 'デデデ'},
    '/hardware/amiibo/lineup/aabt/index.html': {name: 'ルキナ'},
    '/hardware/amiibo/lineup/aabu/index.html': {name: 'ルフレ'},
    '/hardware/amiibo/lineup/aabv/index.html': {name: 'シュルク'},
    '/hardware/amiibo/lineup/aabw/index.html': {name: 'ネス'},
    '/hardware/amiibo/lineup/aabx/index.html': {name: 'Mr.ゲーム＆ウォッチ'},
    '/hardware/amiibo/lineup/aaby/index.html': {name: 'ロボット'},
    '/hardware/amiibo/lineup/aabz/index.html': {name: 'ダックハント'},
    '/hardware/amiibo/lineup/aaca/index.html': {name: 'ソニック'},
    '/hardware/amiibo/lineup/aacb/index.html': {name: 'ロックマン'},
    '/hardware/amiibo/lineup/aacc/index.html': {name: 'パックマン'},
    '/hardware/amiibo/lineup/aace/index.html': {name: 'ミュウツー'},
    '/hardware/amiibo/lineup/aacf/index.html': {name: 'リュカ'},
    '/hardware/amiibo/lineup/aacg/index.html': {name: 'ロイ'},
    '/hardware/amiibo/lineup/aach/index.html': {name: 'リュウ'},
    '/hardware/amiibo/lineup/aack/index.html': {name: 'クラウド'},
    '/hardware/amiibo/lineup/aacl/index.html': {name: 'カムイ'},
    '/hardware/amiibo/lineup/aacm/index.html': {name: 'ベヨネッタ'},
    '/hardware/amiibo/lineup/aacn/index.html': {name: 'クラウド【2Pファイター】'},
    '/hardware/amiibo/lineup/aacp/index.html': {name: 'カムイ【2Pファイター】'},
    '/hardware/amiibo/lineup/aacq/index.html': {name: 'ベヨネッタ【2Pファイター】'},
    '/hardware/amiibo/lineup/abaa/index.html': {name: 'マリオ'},
    '/hardware/amiibo/lineup/abab/index.html': {name: 'ルイージ'},
    '/hardware/amiibo/lineup/abac/index.html': {name: 'ピーチ'},
    '/hardware/amiibo/lineup/abad/index.html': {name: 'ヨッシー'},
    '/hardware/amiibo/lineup/abae/index.html': {name: 'キノピオ'},
    '/hardware/amiibo/lineup/abaf/index.html': {name: 'クッパ'},
    '/hardware/amiibo/lineup/abag/index.html': {name: 'マリオ【ゴールドVer.】'},
    '/hardware/amiibo/lineup/abaj/index.html': {name: 'ロゼッタ'},
    '/hardware/amiibo/lineup/abak/index.html': {name: 'ワリオ'},
    '/hardware/amiibo/lineup/abal/index.html': {name: 'ドンキーコング'},
    '/hardware/amiibo/lineup/abam/index.html': {name: 'ディディーコング'},
    '/hardware/amiibo/lineup/aban/index.html': {name: 'デイジー'},
    '/hardware/amiibo/lineup/abap/index.html': {name: 'ワルイージ'},
    '/hardware/amiibo/lineup/abaq/index.html': {name: 'テレサ'},
    '/hardware/amiibo/lineup/abar/index.html': {name: 'クリボー'},
    '/hardware/amiibo/lineup/abas/index.html': {name: 'ノコノコ'},
    '/hardware/amiibo/lineup/abat/index.html': {name: 'マリオ【ウェディングスタイル】'},
    '/hardware/amiibo/lineup/abau/index.html': {name: 'ピーチ【ウェディングスタイル】'},
    '/hardware/amiibo/lineup/abav/index.html': {name: 'クッパ【ウェディングスタイル】'},
    '/hardware/amiibo/lineup/acaa/index.html': {name: 'ちびロボ'},
    '/hardware/amiibo/lineup/aeaa/index.html': {name: 'ガール'},
    '/hardware/amiibo/lineup/aeab/index.html': {name: 'ボーイ'},
    '/hardware/amiibo/lineup/aeac/index.html': {name: 'イカ'},
    '/hardware/amiibo/lineup/aead/index.html': {name: 'アオリ'},
    '/hardware/amiibo/lineup/aeae/index.html': {name: 'ホタル'},
    '/hardware/amiibo/lineup/aeaf/index.html': {name: 'ガール【ライムグリーン】'},
    '/hardware/amiibo/lineup/aeag/index.html': {name: 'ボーイ【パープル】'},
    '/hardware/amiibo/lineup/aeah/index.html': {name: 'イカ【オレンジ】'},
    '/hardware/amiibo/lineup/aeaj/index.html': {name: 'ガール【ネオンピンク】'},
    '/hardware/amiibo/lineup/aeak/index.html': {name: 'ボーイ【ネオングリーン】'},
    '/hardware/amiibo/lineup/aeal/index.html': {name: 'イカ【ネオンパープル】'},
    '/hardware/amiibo/lineup/afaa/index.html': {name: 'マリオ 【クラシックカラー】'},
    '/hardware/amiibo/lineup/afab/index.html': {name: 'マリオ 【モダンカラー】'},
    '/hardware/amiibo/lineup/ahaa/index.html': {name: 'ショベルナイト'},
    '/hardware/amiibo/lineup/ajaa/index.html': {name: 'しずえ【冬服】'},
    '/hardware/amiibo/lineup/ajab/index.html': {name: 'とたけけ'},
    '/hardware/amiibo/lineup/ajac/index.html': {name: 'きぬよ'},
    '/hardware/amiibo/lineup/ajad/index.html': {name: 'たぬきち'},
    '/hardware/amiibo/lineup/ajae/index.html': {name: 'ケント'},
    '/hardware/amiibo/lineup/ajaf/index.html': {name: 'タクミ'},
    '/hardware/amiibo/lineup/ajag/index.html': {name: 'リサ'},
    '/hardware/amiibo/lineup/ajah/index.html': {name: 'カイゾー'},
    '/hardware/amiibo/lineup/ajaj/index.html': {name: 'フータ'},
    '/hardware/amiibo/lineup/ajak/index.html': {name: 'フーコ'},
    '/hardware/amiibo/lineup/ajal/index.html': {name: 'リセットさん'},
    '/hardware/amiibo/lineup/ajam/index.html': {name: 'シャンク'},
    '/hardware/amiibo/lineup/ajan/index.html': {name: 'しずえ【夏服】'},
    '/hardware/amiibo/lineup/ajap/index.html': {name: 'みしらぬネコ'},
    '/hardware/amiibo/lineup/ajaq/index.html': {name: 'まめきち＆つぶきち'},
    '/hardware/amiibo/lineup/ajar/index.html': {name: 'かっぺい'},
    '/hardware/amiibo/lineup/akaa/index.html': {name: 'ウルフリンク 【トワイライトプリンセス】'},
    '/hardware/amiibo/lineup/akab/index.html': {name: 'リンク【時のオカリナ】'},
    '/hardware/amiibo/lineup/akac/index.html': {name: 'リンク【ムジュラの仮面】'},
    '/hardware/amiibo/lineup/akad/index.html': {name: 'リンク【トワイライトプリンセス】'},
    '/hardware/amiibo/lineup/akae/index.html': {name: 'リンク【スカイウォードソード】'},
    '/hardware/amiibo/lineup/akaf/index.html': {name: 'リンク【ゼルダの伝説】'},
    '/hardware/amiibo/lineup/akag/index.html': {name: 'トゥーンリンク【風のタクト】'},
    '/hardware/amiibo/lineup/akaj/index.html': {name: 'ゼルダ【風のタクト】'},
    '/hardware/amiibo/lineup/akak/index.html': {name: 'リンク(弓)【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/akal/index.html': {name: 'リンク(騎乗)【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/akam/index.html': {name: 'ガーディアン【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/akan/index.html': {name: 'ゼルダ【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/akaq/index.html': {name: 'ダルケル【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/akar/index.html': {name: 'ウルボザ【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/akas/index.html': {name: 'ミファー【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/akat/index.html': {name: 'リーバル【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/akau/index.html': {name: 'ボコブリン【ブレス オブ ザ ワイルド】'},
    '/hardware/amiibo/lineup/alaa/index.html': {name: 'カービィ'},
    '/hardware/amiibo/lineup/alab/index.html': {name: 'メタナイト'},
    '/hardware/amiibo/lineup/alac/index.html': {name: 'デデデ大王'},
    '/hardware/amiibo/lineup/alad/index.html': {name: 'ワドルディ'},
    '/hardware/amiibo/lineup/amaa/index.html': {name: '隻眼のリオレウス＆ライダー（男の子）'},
    '/hardware/amiibo/lineup/amab/index.html': {name: '隻眼のリオレウス＆ライダー（女の子）'},
    '/hardware/amiibo/lineup/amac/index.html': {name: 'ナビルー'},
    '/hardware/amiibo/lineup/amad/index.html': {name: 'リオレイア＆シュヴァル'},
    '/hardware/amiibo/lineup/amae/index.html': {name: 'ベリオロス（ヒョウガ）＆アユリア'},
    '/hardware/amiibo/lineup/amaf/index.html': {name: 'クルペッコ＆ダン先輩'},
    '/hardware/amiibo/lineup/anaa/index.html': {name: 'キュービィ'},
    '/hardware/amiibo/lineup/apaa/index.html': {name: 'ピクミン'},
    '/hardware/amiibo/lineup/aqaa/index.html': {name: 'アルム'},
    '/hardware/amiibo/lineup/aqab/index.html': {name: 'セリカ'},
    '/hardware/amiibo/lineup/aqac/index.html': {name: 'クロム'},
    '/hardware/amiibo/lineup/aqad/index.html': {name: 'チキ'},
    '/hardware/amiibo/lineup/araa/index.html': {name: 'サムス・アラン'},
    '/hardware/amiibo/lineup/arab/index.html': {name: 'メトロイド'},
    '/hardware/amiibo/lineup/ma3a/index.html': {name: 'どうぶつの森amiiboカード 第１弾'},
    '/hardware/amiibo/lineup/ma3b/index.html': {name: 'どうぶつの森amiiboカード 第２弾'},
    '/hardware/amiibo/lineup/ma3c/index.html': {name: 'どうぶつの森amiiboカード 第３弾'},
    '/hardware/amiibo/lineup/ma3d/index.html': {name: 'どうぶつの森amiiboカード 第４弾'},
    '/hardware/amiibo/lineup/md5a/index.html': {name: '『マリオスポーツ スーパースターズ』amiiboカード'},
    '/hardware/amiibo/lineup/me2b/index.html': {name: '『とびだせ どうぶつの森 amiibo+』amiiboカード 【サンリオキャラクターズコラボ】'},
    '/hardware/amiibo/lineup/me3a/index.html': {name: '『とびだせ どうぶつの森 amiibo+』amiiboカード'},
    '/hardware/amiibo/lineup/yaaa/index.html': {name: 'あみぐるみヨッシー みどり'},
    '/hardware/amiibo/lineup/yaab/index.html': {name: 'あみぐるみヨッシー ピンク'},
    '/hardware/amiibo/lineup/yaac/index.html': {name: 'あみぐるみヨッシー みずいろ'},
    '/hardware/amiibo/lineup/yaad/index.html': {name: 'あみぐるみヨッシー ビッグ'},
    '/hardware/amiibo/lineup/yaae/index.html': {name: 'あみぐるみポチ'},
    '/hardware/amiibo/lineup/aacz/index.html': {name: 'インクリング'},
    '/hardware/amiibo/lineup/aacw/index.html': {name: 'リドリー'},
    '/hardware/amiibo/lineup/aacv/index.html': {name: 'ウルフ'},
    '/hardware/amiibo/lineup/aeap/index.html': {name: 'タコガール'},
    '/hardware/amiibo/lineup/aeaq/index.html': {name: 'タコボーイ'},
    '/hardware/amiibo/lineup/aear/index.html': {name: 'タコ'},
    '/hardware/amiibo/lineup/akav/index.html': {name: 'リンク【夢をみる島】'},
    '/hardware/amiibo/lineup/aadj/index.html': {name: 'シモン'},
    '/hardware/amiibo/lineup/aada/index.html': {name: 'フシギソウ'},
    '/hardware/amiibo/lineup/aadb/index.html': {name: 'ゼニガメ'},
    '/hardware/amiibo/lineup/aadh/index.html': {name: 'スネーク'},
    '/hardware/amiibo/lineup/aade/index.html': {name: 'ポケモントレーナー'},
    '/hardware/amiibo/lineup/aadc/index.html': {name: 'ピチュー'},
    '/hardware/amiibo/lineup/aacu/index.html': {name: 'しずえ'},
    '/hardware/amiibo/lineup/aadg/index.html': {name: 'ケン'},
    '/hardware/amiibo/lineup/aact/index.html': {name: 'こどもリンク'},
    '/hardware/amiibo/lineup/aacr/index.html': {name: 'デイジー'},
    '/hardware/amiibo/lineup/aadl/index.html': {name: 'パックンフラワー'},
    '/hardware/amiibo/lineup/aacs/index.html': {name: 'キングクルール'},
    '/hardware/amiibo/lineup/aadk/index.html': {name: 'リヒター'},
    '/hardware/amiibo/lineup/aacx/index.html': {name: 'ダークサムス'},
    '/hardware/amiibo/lineup/aadm/index.html': {name: 'ジョーカー'},
    '/hardware/amiibo/lineup/aadn/index.html': {name: '勇者'},

    '/hardware/wiiu/index.html': {name: '本体・amiibo：Wii U'},
    '/hardware/wiiu/lineup/index.html': {name: '本体ラインナップ'},
    '/hardware/wiiu/accessories/index.html': {name: '周辺機器'},
    '/hardware/wiiu/parts/index.html': {name: '各部機能'},
    '/hardware/wiiu/specs/index.html': {name: '主な仕様'},
    '/hardware/wiiu/dlsoft/arakajime/index.html': {name: 'あらかじめダウンロードとは？'},
    '/hardware/wiiu/built-in/index.html': {name: '内蔵ソフト・その他'},
    '/hardware/wiiu/miiverse/index.html': {name: 'Miiverse'},
    '/hardware/wiiu/internetbrowser/index.html': {name: 'インターネットブラウザー'},
    '/hardware/wiiu/internetbrowser/extended_functionality.html': {name: 'インターネットブラウザーの拡張機能について'},
    '/hardware/wiiu/postimage/index.html': {name: 'Wii U画像投稿ツール'},
    '/hardware/wiiu/tvii/index.html': {name: 'Nintendo TVii'},
    '/hardware/wiiu/chat/index.html': {name: 'Wii U Chat'},
    '/hardware/wiiu/miistudio/index.html': {name: 'Miiスタジオ'},
    '/hardware/wiiu/features/eshop/index.html': {name: 'ニンテンドーeショップとは？'},
    '/hardware/wiiu/features/index.html': {name: 'Wiiのソフトで遊ぶ'},

    '/hardware/classicmini/index.html': {name: '本体・amiibo：ニンテンドークラシックミニシリーズ'},

    '/clvs/index.html': {name: '本体・amiibo：ニンテンドークラシックミニ スーパーファミコン'},
    '/clvs/soft/index.html': {name: '収録タイトル一覧'},
    '/clvs/soft/contora.html': {name: '魂斗羅スピリッツ'},
    '/clvs/soft/f_emblem.html': {name: 'ファイアーエムブレム 紋章の謎'},
    '/clvs/soft/f_zero.html': {name: 'F-ZERO'},
    '/clvs/soft/ff6.html': {name: 'ファイナルファンタジーVI'},
    '/clvs/soft/goemon.html': {name: 'がんばれゴエモン ゆき姫救出絵巻'},
    '/clvs/soft/kirby.html': {name: '星のカービィ スーパーデラックス'},
    '/clvs/soft/makaimura.html': {name: '超魔界村®'},
    '/clvs/soft/mario_kart.html': {name: 'スーパーマリオカート'},
    '/clvs/soft/mario_rpg.html': {name: 'スーパーマリオＲＰＧ'},
    '/clvs/soft/mario_world.html': {name: 'スーパーマリオワールド'},
    '/clvs/soft/mario_yossy.html': {name: 'スーパーマリオ ヨッシーアイランド'},
    '/clvs/soft/panel.html': {name: 'パネルでポン'},
    '/clvs/soft/rockman.html': {name: 'ロックマン®X'},
    '/clvs/soft/s_donkey_kong.html': {name: 'スーパードンキーコング'},
    '/clvs/soft/s_fox.html': {name: 'スターフォックス'},
    '/clvs/soft/s_fox2.html': {name: 'スターフォックス2'},
    '/clvs/soft/s_metroid.html': {name: 'スーパーメトロイド'},
    '/clvs/soft/seiken.html': {name: '聖剣伝説2'},
    '/clvs/soft/sf_soccer.html': {name: 'スーパーフォーメーションサッカー'},
    '/clvs/soft/sss2.html': {name: 'スーパーストリートファイター®Ⅱ ザニューチャレンジャーズ'},
    '/clvs/soft/zelda.html': {name: 'ゼルダの伝説 神々のトライフォース'},
    '/clvs/spec/index.html': {name: '主な仕様'},
    '/clvs/interview/index.html': {name: 'インタビュー'},

    '/clv/index.html': {name: '本体・amiibo：ニンテンドークラシックミニ ファミリーコンピュータ'},
    '/clv/features.html': {name: '本体の特長'},
    '/clv/interview.html': {name: 'インタビュー'},
    '/clv/spec.html': {name: '主な仕様'},
    '/clv/sp/index.html': {name: '本体・amiibo：ニンテンドークラシックミニ ファミリーコンピュータ', parent: '/index.html'},
    '/clv/sp/features.html': {name: '本体の特長'},
    '/clv/sp/interview.html': {name: 'インタビュー'},
    '/clv/sp/spec.html': {name: '主な仕様'},
    '/clv/sp/detail/adventureoflink.html': {name: 'リンクの冒険'},
    '/clv/sp/detail/atlantis.html': {name: 'アトランチスの謎'},
    '/clv/sp/detail/balloonfight.html': {name: 'バルーンファイト'},
    '/clv/sp/detail/donkeykong.html': {name: 'ドンキーコング'},
    '/clv/sp/detail/doubledragon.html': {name: 'ダブルドラゴンII The Revenge'},
    '/clv/sp/detail/downtownkoushin.html': {name: 'ダウンタウン熱血行進曲 それゆけ大運動会'},
    '/clv/sp/detail/downtownmonogatari.html': {name: 'ダウンタウン熱血物語'},
    '/clv/sp/detail/dracula.html': {name: '悪魔城ドラキュラ'},
    '/clv/sp/detail/drmario.html': {name: 'ドクターマリオ'},
    '/clv/sp/detail/excitebike.html': {name: 'エキサイトバイク'},
    '/clv/sp/detail/ff3.html': {name: 'ファイナルファンタジー®III'},
    '/clv/sp/detail/galaga.html': {name: 'ギャラガ'},
    '/clv/sp/detail/gradius.html': {name: 'グラディウス'},
    '/clv/sp/detail/iceclimber.html': {name: 'アイスクライマー'},
    '/clv/sp/detail/kirby.html': {name: '星のカービィ夢の泉の物語'},
    '/clv/sp/detail/makaimura.html': {name: '魔界村®'},
    '/clv/sp/detail/mariobros.html': {name: 'マリオブラザーズ'},
    '/clv/sp/detail/mariogolf.html': {name: 'マリオオープンゴルフ '},
    '/clv/sp/detail/metroid.html': {name: 'メトロイド'},
    '/clv/sp/detail/ninja.html': {name: '忍者龍剣伝'},
    '/clv/sp/detail/pacman.html': {name: 'パックマン '},
    '/clv/sp/detail/rockman2.html': {name: 'ロックマン®2 Dr.ワイリーの謎 '},
    '/clv/sp/detail/solomon.html': {name: 'ソロモンの鍵'},
    '/clv/sp/detail/supercontra.html': {name: 'スーパー魂斗羅'},
    '/clv/sp/detail/supermario.html': {name: 'スーパーマリオブラザーズ'},
    '/clv/sp/detail/supermario3.html': {name: 'スーパーマリオブラザーズ3'},
    '/clv/sp/detail/supermariousa.html': {name: 'スーパーマリオUSA'},
    '/clv/sp/detail/tsuppariozumo.html': {name: 'つっぱり大相撲'},
    '/clv/sp/detail/yiearkungfu.html': {name: 'イー・アル・カンフー'},
    '/clv/sp/detail/zelda.html': {name: 'ゼルダの伝説'},

    '/clvj/index.html': {name: '本体・amiibo：ニンテンドークラシックミニ　ファミリーコンピュータ 週刊少年ジャンプ創刊50周年記念バージョン'},
    '/clvj/sp/index.html': {name: '本体・amiibo：ニンテンドークラシックミニ　ファミリーコンピュータ 週刊少年ジャンプ創刊50周年記念バージョン', parent: '/index.html'},


    '/software/switch/index.html': {name: 'ゲームソフト：Nintendo Switchソフト'},
    '/software/switch/megamitensei/index.html': {name: '真・女神転生 シリーズ最新作'},
    '/switch/2018summer/index.html': {name: 'Nintendo Switch いつでも、どこでも、誰とでも。2018夏', parent: '/hardware/switch/index.html'},
    '/switch/rocketleague/index.html': {name: 'ロケットリーグ', parent: '/software/switch/index.html'},
    '/switch/sonicforces/index.html': {name: 'ソニックフォース', parent: '/software/switch/index.html'},
    '/switch/ac2ga/index.html': {name: 'マリオ＋ラビッツ キングダムバトル', parent: '/software/switch/index.html'},
    '/switch/aea2a/index.html': {name: 'ヨッシー for Nintendo Switch (仮称)', parent: '/software/switch/index.html'},
    '/switch/ah26a/index.html': {name: '星のカービィ スターアライズ', parent: '/software/switch/index.html'},
    '/switch/baata/index.html': {name: 'カラオケJOYSOUND for Nintendo Switch', parent: '/software/switch/index.html'},
    '/switch/_wolf/index.html': {name: 'Wolfenstein II: The New Colossus', parent: '/software/switch/index.html'},
    '/switch/ag3ja/index.html': {name: 'ルイージマンション３', parent: '/software/switch/index.html'},
    '/switch/ar3na/index.html': {name: 'ゼルダの伝説 夢をみる島', parent: '/software/switch/index.html'},
    '/switch/ampna/index.html': {name: 'ピクミン３ デラックス', parent: '/software/switch/index.html'},

    '/software/3ds/index.html': {name: 'ゲームソフト：ニンテンドー3DSソフト'},

    '/software/wiiu/index.html': {name: 'ゲームソフト：Wii Uソフト'},
    '/wiiu/software/eshop/index.html': {name: 'ニンテンドーeショップとは？', parent: '/software/wiiu/index.html'},
    '/wiiu/software/wii/index.html': {name: 'Wiiディスクソフト（ダウンロード版）', parent: '/software/wiiu/index.html'},

    '/software/smartphone/index.html': {name: 'ゲームソフト：スマートフォン向けアプリ'},

    '/software/campaign/index.html': {name: 'ゲームソフト：キャンペーン・セール情報'},

    '/software/trial/index.html': {name: 'ゲームソフト：体験版が遊べるソフト'},
    '/software/trial/nintendocheckin.html': {name: 'ニンテンドーチェックイン'},
    '/software/trial/gamefront.html': {name: 'ニンテンドーゲームフロント'},
    '/software/trial/station.html': {name: 'ニンテンドー3DSステーション'},
    '/software/trial/store.html': {name: 'Nintendo Switchを体験できる店舗'},

    '/software/feature/3ds-sfc_vc-ranking.html': {name: 'スーパーファミコン バーチャルコンソールランキング'},

    '/software/feature/boardgame.html': {name: 'テーブルゲームであそぶ'},
    '/software/feature/gameawards.html': {name: 'The Game Awards 2018 ノミネート作品特集'},
    '/software/feature/gameawards2019.html': {name: 'The Game Awards 2019 ノミネート作品特集'},
    '/software/feature/gameseries.html': {name: 'シリーズタイトル'},
    '/software/feature/puzzle.html': {name: 'パズルゲームであそぶ'},
    '/software/feature/rhythm.html': {name: 'リズムゲームであそぶ'},
    '/software/feature/party.html': {name: 'パーティーゲームであそぶ'},
    '/software/feature/switchshare.html': {name: '楽しいをおすそわけ'},
    '/software/feature/sports.html': {name: 'スポーツゲームであそぶ'},
    '/software/feature/rpg.html': {name: 'RPGであそぶ'},
    '/software/feature/pokemon.html': {name: 'ポケモン特集'},
    '/software/feature/otona.html': {name: 'オトナのゲーム特集'},
    '/software/feature/strategy.html': {name: 'ストラテジーゲームであそぶ'},
    '/software/feature/otome.html': { name: '乙女ゲーム特集' },
    '/software/feature/otome_agf2019.html': {name: 'アニメイトガールズフェスティバル2019 Nintendo Switch ブース概要'},
    '/software/feature/cat.html': {name: 'ねこのゲームであそぶ'},
    '/software/feature/rogue_like.html': {name: 'ローグライクゲームであそぶ'},
    '/software/feature/text_adventure.html': { name: 'テキストアドベンチャーゲームであそぶ' },
    '/software/feature/2019winter.html': {name: 'この冬のプレゼントにおすすめのソフト'},
    '/software/feature/players-ranking2019.html': {name: '2019年 年間おすすめランキング'},
    '/software/feature/package-ranking2019.html': {name: '2019年 年間ダウンロードランキング TOP30 ～パッケージソフト ダウンロード版編～'},
    '/software/feature/download-ranking2019.html': {name: '2019年 年間ダウンロードランキング TOP30 ～ダウンロード専用ソフト編～'},
    '/software/feature/engaging.html': {name: 'たっぷり楽しめるソフト'},
    '/software/feature/nintendoswitchonline.html': {name: 'Nintendo Switch Onlineでオンラインゲームをあそぶ'},
    '/software/feature/3d_shooting.html': {name: 'シューティングゲームであそぶ [3D編]'},
    '/software/feature/2d_shooting.html': {name: 'シューティングゲームであそぶ [2D編]'},

    '/software/free/index.html': {name: 'ゲームソフト：無料でダウンロードできるソフト'},

    '/software/howtodl/index.html': {name: 'ゲームソフト：ソフトをダウンロード購入する'},
    '/software/howtodl/prepaidcard/index.html': {name: 'ニンテンドープリペイドカードについて'},

    '/3ds/pokemon_crystal/index.html': {name: 'ポケットモンスター クリスタルバージョン（ニンテンドー3DSバーチャルコンソール）', parent: '/software/3ds/index.html'},
    '/3ds/pokemon_goldsilver_dlcard/index.html': {name: 'ポケットモンスター 金・銀（ニンテンドー3DSバーチャルコンソール）', parent: '/software/3ds/index.html'},


    '/parents/index.html': {name: '任天堂から保護者のみなさまへ'},

    '/parents/3ds-wiiu/index.html': {name: 'ニンテンドー3DS / Wii U'},
    '/parents/3ds-wiiu/browser.html': {name: 'ウェブサイトの閲覧'},
    '/parents/3ds-wiiu/download.html': {name: 'クレジットカードの利用'},
    '/parents/3ds-wiiu/communication.html': {name: 'コミュニケーション'},
    '/parents/sp/3ds-wiiu/index.html': {name: 'ニンテンドー3DS / Wii U'},
    '/parents/sp/3ds-wiiu/browser.html': {name: 'ウェブサイトの閲覧'},
    '/parents/sp/3ds-wiiu/download.html': {name: 'クレジットカードの利用'},
    '/parents/sp/3ds-wiiu/communication.html': {name: 'コミュニケーション'},

    '/parents/switch/index.html': {name: 'Nintendo Switch'},
    '/parents/switch/play/index.html': {name: 'ゲームのプレイ時間をみまもりたい'},
    '/parents/switch/download/index.html': {name: 'ゲームソフトなどのダウンロード購入を制限したい'},
    '/parents/switch/communication/index.html': {name: 'ほかの人との自由なコミュニケーションを制限したい'},


    '/schedule/index.html': {name: '発売スケジュール'},
    '/social/index.html': {name: 'ソーシャルメディアアカウント'},
    '/summersale2017/index.html': {name: 'ニンテンドーeショップ　ヒートアップセール！'},
    '/nintendozone/index.html': {name: 'ニンテンドーゾーン'},
    '/about_hp.html': {name: '任天堂ウェブサイトポリシー'},
    '/anzen/index.html': {name: '健康と安全のために'},
    '/others/index.html': {name: 'トランプ・花札など'},
    '/others/playing_cards/index.html': {name: 'トランプ：ラインナップ'},
    '/others/playing_cards/lineup/splatoon/index.html': {name: 'スプラトゥーントランプ'},
    '/others/playing_cards/lineup/mario/index.html': {name: 'マリオトランプ'},
    '/others/playing_cards/lineup/zelda/index.html': {name: 'ゼルダトランプ'},
    '/others/playing_cards/lineup/kirby/index.html': {name: '星のカービィトランプ'},
    '/others/playing_cards/lineup/standard/index.html': {name: 'スタンダードトランプ'},
    '/others/playing_cards/howtoplay/index.html': {name: 'トランプの歴史・遊びかた'},
    '/others/playing_cards/howtoplay/poker/index.html': {name: 'ポーカー'},
    '/others/playing_cards/howtoplay/seven_bridge/index.html': {name: 'セブンブリッジ'},
    '/others/playing_cards/howtoplay/american_page_one/index.html': {name: 'アメリカン・ページワン'},
    '/others/playing_cards/howtoplay/doubt/index.html': {name: 'ダウト'},
    '/others/playing_cards/howtoplay/lamy/index.html': {name: 'ラミー'},
    '/others/playing_cards/howtoplay/dull_person/index.html': {name: 'スローモー'},
    '/others/playing_cards/howtoplay/speed/index.html': {name: 'スピード'},


    '/others/playing_cards/original/index.html': {name: 'オリジナルトランプのご注文'},
    '/others/hanafuda_kabufuda/index.html': {name: '花札・株札：ラインナップ'},
    '/others/hanafuda_kabufuda/mario/index.html': {name: 'マリオ花札'},
    '/others/hanafuda_kabufuda/howtoplay/index.html': {name: '花札の歴史・遊びかた'},
    '/others/mahjong/index.html': {name: '麻雀'},
    '/others/hyakuninishu/index.html': {name: '小倉百人一首'},
    '/others/shogi/index.html': {name: '将棋'},
    '/others/igo/index.html': {name: '囲碁'},

    '/officialstore/index.html': {name: 'Nintendo TOKYO'},
    '/officialstore/goods/index.html': {name: 'グッズ'},
    '/officialstore/faq/index.html': { name: 'よくある質問' },
    '/officialstore/prevention/index.html': {name: '新型コロナウイルス感染拡大防止に向けた取り組みとお客様へのお願い'},
    '/officialstore/entry/index.html': {name: '抽選販売'},

    '/mynintendo/app/index.html': {name: 'My Nintendo（スマートフォン向けアプリ）'},

    '/news/index.html': {name: '更新情報'},
    '/sitemap/index.html': {name: 'サイトマップ'},
    '/search/index.html': {name: 'さがす'},
  }
});
